### ISSUE TITLE
Importing Blazeface and FaceDetector

### ISSUE THREAD

**Issue by ZPBerg** [PurdueCAM2Project/Embedded2#11]
I need to import the FaceDetector class as well as Blazeface for a script (which would be in scripts/). Do I need to do one of [these](https://stackoverflow.com/questions/4383571/importing-files-from-different-folder) to make it work? 

Also if there's a better place for asking a question like this, someone let me know.

**Comment by stephend017** [comment]
So this is a good question because importing in python can be a pain. So I'm gonna leave a quick overview of importing in python here and hopefully that will answer your question. 

### Include an `__init__.py` in every source directory
this is how python knows this is a source directory. without this file your imports won't work.

```python
# example file structure

application
+--- __init__.py
+--- mymodule
     +--- __init__.py
     +--- myfile.py
```

### Always use relative imports 
``` python
# this is an absolute import, its good because its a fully qualified path and won't result in any errors.
# also it allows us to know exactly what were importing here and don't create any confusion
from application.mypackage import mymodule

# this is a relative import. it is bad because if we refactor our code we risk introducing a breaking a change. 
# also this creates *some* ambiguity on where this module is located. 
from . import mymodule 
```

### Use the `from` and `as` keywords
imagine we have a long import like the following
```python
import myapplication.mymodule.myothermodule.myfunction
```
this is really long and obnoxious since we need to type that entire thing out to use that function. to show that here is the function being invoked
```python
myapplication.mymodule.myothermodule.myfunction()
```

the solution to this is using `as` and `from` heres a few examples

```python
# example using from
from myapplication.mymodule.myothermodule import myfunction

# example using as
import myapplication.mymodule.myothermodule.myfunction as myfunction
```
this then would reduce the code usage to
```python
myfunction() 
```
both of these examples are valid however stylistically the first is usually preferred

### Final Thoughts
this should be enough to get you started. In general if you follow these rules you wont run into much trouble. if you have any follow up questions please comment with them below.

**Comment by ZPBerg** [comment]
Did you mean to say 'Always use absolute imports'?

**Comment by stephend017** [comment]
Yes my bad
