### ISSUE TITLE
Using a script as a standalone but still importing our methods

### ISSUE THREAD

**Issue by ZPBerg** [PurdueCAM2Project/Embedded2#14]
I'm writing a script that will exist on the HELPS machine and it's going to query our database so I need to make use of the functions in src/jetson/db. Should I put this script in the scripts/ folder (or maybe the db/ folder, even though it doesn't really make sense there)? Should I clone our entire repo onto the HELPS machine so I have access to the functions I need?

**Comment by stephend017** [comment]
It should probably exist in the scripts folder. I don't think I mentioned this when discussing scripts last time but they can make use of the code in the rest of the application. I think the confusion comes from the location of `db` code. It doesn't make sense for it to be specific to jetson at this point since jetson isn't the only place its used. maybe you could make that refactor.

**Comment by pawar4** [comment]
db Folder can been moved out of the jetson folder so I am going to assume this issue was resolved
